apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-ui-dataplatform-dsaas-deploy
  namespace: eda-ui
  labels:
    app.kubernetes.io/name: eda-ui-dataplatform-dsaas-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eda-ui-dataplatform-dsaas-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eda-ui-dataplatform-dsaas-deploy
    spec:
      containers:
      - name: eda-ui-dataplatform-dsaas-deploy
        image: 432372222409.dkr.ecr.us-east-1.amazonaws.com/eda/ui/dataplatform/dsaas:latest
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: false

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config